### ISSUE TITLE
Another faucet request for validator on cosmoshub-4-upgrade-testnet

### ISSUE THREAD

**Issue by kmur911** [b-harvest/gravity-dex-upgrade-test#3]
apologies, I requested funds for an address which apparently i can't find the private key for. can you please send testnet funds to these two addresses just in case something goes wrong?

cosmos1c3dth20f7cmgzm2sal4vclpujwnkp89vqrs5sz
cosmos1vw4ucaeagtduv5ep4sa95e3aqzqpsk5meda08c

**Comment by nodebreaker0-0** [comment]
Please check your account
